export const mock5days = {
    cod: '200',
    message: 0,
    cnt: 40,
    list: [
        {
            dt: 1681408800,
            main: {
                temp: 12.82,
                feels_like: 12.3,
                temp_min: 12.18,
                temp_max: 12.82,
                pressure: 1005,
                sea_level: 1005,
                grnd_level: 1002,
                humidity: 82,
                temp_kf: 0.64,
            },
            weather: [
                {
                    id: 801,
                    main: 'Clouds',
                    description: 'few clouds',
                    icon: '02n',
                },
            ],
            clouds: {
                all: 20,
            },
            wind: {
                speed: 11.52,
                deg: 354,
                gust: 16.31,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'n',
            },
            dt_txt: '2023-04-13 18:00:00',
        },
        {
            dt: 1681419600,
            main: {
                temp: 12.55,
                feels_like: 11.95,
                temp_min: 12.01,
                temp_max: 12.55,
                pressure: 1006,
                sea_level: 1006,
                grnd_level: 1004,
                humidity: 80,
                temp_kf: 0.54,
            },
            weather: [
                {
                    id: 500,
                    main: 'Rain',
                    description: 'light rain',
                    icon: '10n',
                },
            ],
            clouds: {
                all: 33,
            },
            wind: {
                speed: 7.65,
                deg: 345,
                gust: 12.12,
            },
            visibility: 10000,
            pop: 0.5,
            rain: {
                '3h': 0.48,
            },
            sys: {
                pod: 'n',
            },
            dt_txt: '2023-04-13 21:00:00',
        },
        {
            dt: 1681430400,
            main: {
                temp: 12.69,
                feels_like: 11.95,
                temp_min: 12.62,
                temp_max: 12.69,
                pressure: 1006,
                sea_level: 1006,
                grnd_level: 1005,
                humidity: 74,
                temp_kf: 0.07,
            },
            weather: [
                {
                    id: 803,
                    main: 'Clouds',
                    description: 'broken clouds',
                    icon: '04n',
                },
            ],
            clouds: {
                all: 60,
            },
            wind: {
                speed: 3.17,
                deg: 357,
                gust: 5.33,
            },
            visibility: 10000,
            pop: 0.31,
            sys: {
                pod: 'n',
            },
            dt_txt: '2023-04-14 00:00:00',
        },
        {
            dt: 1681441200,
            main: {
                temp: 12.97,
                feels_like: 12.12,
                temp_min: 12.97,
                temp_max: 12.97,
                pressure: 1010,
                sea_level: 1010,
                grnd_level: 1007,
                humidity: 69,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04d',
                },
            ],
            clouds: {
                all: 86,
            },
            wind: {
                speed: 4.21,
                deg: 222,
                gust: 6.07,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-04-14 03:00:00',
        },
        {
            dt: 1681452000,
            main: {
                temp: 14.19,
                feels_like: 13.26,
                temp_min: 14.19,
                temp_max: 14.19,
                pressure: 1011,
                sea_level: 1011,
                grnd_level: 1008,
                humidity: 61,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 803,
                    main: 'Clouds',
                    description: 'broken clouds',
                    icon: '04d',
                },
            ],
            clouds: {
                all: 69,
            },
            wind: {
                speed: 6.08,
                deg: 182,
                gust: 7.29,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-04-14 06:00:00',
        },
        {
            dt: 1681462800,
            main: {
                temp: 17.52,
                feels_like: 16.5,
                temp_min: 17.52,
                temp_max: 17.52,
                pressure: 1009,
                sea_level: 1009,
                grnd_level: 1007,
                humidity: 45,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 803,
                    main: 'Clouds',
                    description: 'broken clouds',
                    icon: '04d',
                },
            ],
            clouds: {
                all: 62,
            },
            wind: {
                speed: 5.78,
                deg: 181,
                gust: 8.32,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-04-14 09:00:00',
        },
        {
            dt: 1681473600,
            main: {
                temp: 18.12,
                feels_like: 17.19,
                temp_min: 18.12,
                temp_max: 18.12,
                pressure: 1008,
                sea_level: 1008,
                grnd_level: 1006,
                humidity: 46,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 803,
                    main: 'Clouds',
                    description: 'broken clouds',
                    icon: '04d',
                },
            ],
            clouds: {
                all: 59,
            },
            wind: {
                speed: 11.02,
                deg: 206,
                gust: 14.54,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-04-14 12:00:00',
        },
        {
            dt: 1681484400,
            main: {
                temp: 16.95,
                feels_like: 15.95,
                temp_min: 16.95,
                temp_max: 16.95,
                pressure: 1009,
                sea_level: 1009,
                grnd_level: 1006,
                humidity: 48,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 802,
                    main: 'Clouds',
                    description: 'scattered clouds',
                    icon: '03d',
                },
            ],
            clouds: {
                all: 50,
            },
            wind: {
                speed: 12.56,
                deg: 214,
                gust: 17.75,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-04-14 15:00:00',
        },
        {
            dt: 1681495200,
            main: {
                temp: 15.05,
                feels_like: 14.1,
                temp_min: 15.05,
                temp_max: 15.05,
                pressure: 1010,
                sea_level: 1010,
                grnd_level: 1007,
                humidity: 57,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 802,
                    main: 'Clouds',
                    description: 'scattered clouds',
                    icon: '03n',
                },
            ],
            clouds: {
                all: 44,
            },
            wind: {
                speed: 8.64,
                deg: 227,
                gust: 14.38,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'n',
            },
            dt_txt: '2023-04-14 18:00:00',
        },
        {
            dt: 1681506000,
            main: {
                temp: 12.58,
                feels_like: 11.62,
                temp_min: 12.58,
                temp_max: 12.58,
                pressure: 1011,
                sea_level: 1011,
                grnd_level: 1009,
                humidity: 66,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 800,
                    main: 'Clear',
                    description: 'clear sky',
                    icon: '01n',
                },
            ],
            clouds: {
                all: 5,
            },
            wind: {
                speed: 4.2,
                deg: 287,
                gust: 9.04,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'n',
            },
            dt_txt: '2023-04-14 21:00:00',
        },
        {
            dt: 1681516800,
            main: {
                temp: 11.99,
                feels_like: 10.94,
                temp_min: 11.99,
                temp_max: 11.99,
                pressure: 1013,
                sea_level: 1013,
                grnd_level: 1011,
                humidity: 65,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 800,
                    main: 'Clear',
                    description: 'clear sky',
                    icon: '01n',
                },
            ],
            clouds: {
                all: 8,
            },
            wind: {
                speed: 6.15,
                deg: 335,
                gust: 10.29,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'n',
            },
            dt_txt: '2023-04-15 00:00:00',
        },
        {
            dt: 1681527600,
            main: {
                temp: 12.07,
                feels_like: 10.95,
                temp_min: 12.07,
                temp_max: 12.07,
                pressure: 1016,
                sea_level: 1016,
                grnd_level: 1013,
                humidity: 62,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 801,
                    main: 'Clouds',
                    description: 'few clouds',
                    icon: '02d',
                },
            ],
            clouds: {
                all: 18,
            },
            wind: {
                speed: 5.39,
                deg: 1,
                gust: 9.08,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-04-15 03:00:00',
        },
        {
            dt: 1681538400,
            main: {
                temp: 14.41,
                feels_like: 13.21,
                temp_min: 14.41,
                temp_max: 14.41,
                pressure: 1018,
                sea_level: 1018,
                grnd_level: 1015,
                humidity: 50,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 802,
                    main: 'Clouds',
                    description: 'scattered clouds',
                    icon: '03d',
                },
            ],
            clouds: {
                all: 30,
            },
            wind: {
                speed: 4.18,
                deg: 357,
                gust: 5.24,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-04-15 06:00:00',
        },
        {
            dt: 1681549200,
            main: {
                temp: 16.12,
                feels_like: 14.99,
                temp_min: 16.12,
                temp_max: 16.12,
                pressure: 1019,
                sea_level: 1019,
                grnd_level: 1016,
                humidity: 46,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 800,
                    main: 'Clear',
                    description: 'clear sky',
                    icon: '01d',
                },
            ],
            clouds: {
                all: 7,
            },
            wind: {
                speed: 3.43,
                deg: 29,
                gust: 3.38,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-04-15 09:00:00',
        },
        {
            dt: 1681560000,
            main: {
                temp: 16.15,
                feels_like: 15.05,
                temp_min: 16.15,
                temp_max: 16.15,
                pressure: 1019,
                sea_level: 1019,
                grnd_level: 1016,
                humidity: 47,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 800,
                    main: 'Clear',
                    description: 'clear sky',
                    icon: '01d',
                },
            ],
            clouds: {
                all: 6,
            },
            wind: {
                speed: 2.81,
                deg: 82,
                gust: 3.65,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-04-15 12:00:00',
        },
        {
            dt: 1681570800,
            main: {
                temp: 14.81,
                feels_like: 13.68,
                temp_min: 14.81,
                temp_max: 14.81,
                pressure: 1020,
                sea_level: 1020,
                grnd_level: 1017,
                humidity: 51,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 800,
                    main: 'Clear',
                    description: 'clear sky',
                    icon: '01d',
                },
            ],
            clouds: {
                all: 10,
            },
            wind: {
                speed: 3.15,
                deg: 75,
                gust: 3.9,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-04-15 15:00:00',
        },
        {
            dt: 1681581600,
            main: {
                temp: 13.56,
                feels_like: 12.43,
                temp_min: 13.56,
                temp_max: 13.56,
                pressure: 1022,
                sea_level: 1022,
                grnd_level: 1019,
                humidity: 56,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 800,
                    main: 'Clear',
                    description: 'clear sky',
                    icon: '01n',
                },
            ],
            clouds: {
                all: 9,
            },
            wind: {
                speed: 3.87,
                deg: 23,
                gust: 4.84,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'n',
            },
            dt_txt: '2023-04-15 18:00:00',
        },
        {
            dt: 1681592400,
            main: {
                temp: 10.82,
                feels_like: 9.97,
                temp_min: 10.82,
                temp_max: 10.82,
                pressure: 1023,
                sea_level: 1023,
                grnd_level: 1020,
                humidity: 77,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 800,
                    main: 'Clear',
                    description: 'clear sky',
                    icon: '01n',
                },
            ],
            clouds: {
                all: 5,
            },
            wind: {
                speed: 8.74,
                deg: 6,
                gust: 10.65,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'n',
            },
            dt_txt: '2023-04-15 21:00:00',
        },
        {
            dt: 1681603200,
            main: {
                temp: 9.18,
                feels_like: 5.13,
                temp_min: 9.18,
                temp_max: 9.18,
                pressure: 1024,
                sea_level: 1024,
                grnd_level: 1021,
                humidity: 80,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 801,
                    main: 'Clouds',
                    description: 'few clouds',
                    icon: '02n',
                },
            ],
            clouds: {
                all: 12,
            },
            wind: {
                speed: 9.96,
                deg: 6,
                gust: 12.7,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'n',
            },
            dt_txt: '2023-04-16 00:00:00',
        },
        {
            dt: 1681614000,
            main: {
                temp: 8.92,
                feels_like: 4.8,
                temp_min: 8.92,
                temp_max: 8.92,
                pressure: 1026,
                sea_level: 1026,
                grnd_level: 1024,
                humidity: 75,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 802,
                    main: 'Clouds',
                    description: 'scattered clouds',
                    icon: '03d',
                },
            ],
            clouds: {
                all: 41,
            },
            wind: {
                speed: 9.92,
                deg: 7,
                gust: 12.52,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-04-16 03:00:00',
        },
        {
            dt: 1681624800,
            main: {
                temp: 9.91,
                feels_like: 6.29,
                temp_min: 9.91,
                temp_max: 9.91,
                pressure: 1028,
                sea_level: 1028,
                grnd_level: 1025,
                humidity: 67,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 803,
                    main: 'Clouds',
                    description: 'broken clouds',
                    icon: '04d',
                },
            ],
            clouds: {
                all: 62,
            },
            wind: {
                speed: 9.08,
                deg: 15,
                gust: 10.31,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-04-16 06:00:00',
        },
        {
            dt: 1681635600,
            main: {
                temp: 10.82,
                feels_like: 9.55,
                temp_min: 10.82,
                temp_max: 10.82,
                pressure: 1028,
                sea_level: 1028,
                grnd_level: 1025,
                humidity: 61,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 803,
                    main: 'Clouds',
                    description: 'broken clouds',
                    icon: '04d',
                },
            ],
            clouds: {
                all: 67,
            },
            wind: {
                speed: 7.14,
                deg: 33,
                gust: 7.23,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-04-16 09:00:00',
        },
        {
            dt: 1681646400,
            main: {
                temp: 10.11,
                feels_like: 8.8,
                temp_min: 10.11,
                temp_max: 10.11,
                pressure: 1028,
                sea_level: 1028,
                grnd_level: 1025,
                humidity: 62,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 803,
                    main: 'Clouds',
                    description: 'broken clouds',
                    icon: '04d',
                },
            ],
            clouds: {
                all: 58,
            },
            wind: {
                speed: 6.12,
                deg: 50,
                gust: 5.66,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-04-16 12:00:00',
        },
        {
            dt: 1681657200,
            main: {
                temp: 8.71,
                feels_like: 5.64,
                temp_min: 8.71,
                temp_max: 8.71,
                pressure: 1029,
                sea_level: 1029,
                grnd_level: 1026,
                humidity: 64,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04d',
                },
            ],
            clouds: {
                all: 93,
            },
            wind: {
                speed: 5.89,
                deg: 31,
                gust: 5.93,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-04-16 15:00:00',
        },
        {
            dt: 1681668000,
            main: {
                temp: 8.27,
                feels_like: 5.41,
                temp_min: 8.27,
                temp_max: 8.27,
                pressure: 1030,
                sea_level: 1030,
                grnd_level: 1027,
                humidity: 62,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04n',
                },
            ],
            clouds: {
                all: 97,
            },
            wind: {
                speed: 5.04,
                deg: 19,
                gust: 5.34,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'n',
            },
            dt_txt: '2023-04-16 18:00:00',
        },
        {
            dt: 1681678800,
            main: {
                temp: 8.32,
                feels_like: 6.06,
                temp_min: 8.32,
                temp_max: 8.32,
                pressure: 1028,
                sea_level: 1028,
                grnd_level: 1026,
                humidity: 56,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04n',
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 3.76,
                deg: 30,
                gust: 3.86,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'n',
            },
            dt_txt: '2023-04-16 21:00:00',
        },
        {
            dt: 1681689600,
            main: {
                temp: 8.72,
                feels_like: 7.35,
                temp_min: 8.72,
                temp_max: 8.72,
                pressure: 1027,
                sea_level: 1027,
                grnd_level: 1024,
                humidity: 53,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04n',
                },
            ],
            clouds: {
                all: 85,
            },
            wind: {
                speed: 2.44,
                deg: 71,
                gust: 3.1,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'n',
            },
            dt_txt: '2023-04-17 00:00:00',
        },
        {
            dt: 1681700400,
            main: {
                temp: 9.38,
                feels_like: 9.01,
                temp_min: 9.38,
                temp_max: 9.38,
                pressure: 1027,
                sea_level: 1027,
                grnd_level: 1024,
                humidity: 53,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 803,
                    main: 'Clouds',
                    description: 'broken clouds',
                    icon: '04d',
                },
            ],
            clouds: {
                all: 82,
            },
            wind: {
                speed: 1.44,
                deg: 142,
                gust: 2.66,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-04-17 03:00:00',
        },
        {
            dt: 1681711200,
            main: {
                temp: 11.17,
                feels_like: 9.62,
                temp_min: 11.17,
                temp_max: 11.17,
                pressure: 1027,
                sea_level: 1027,
                grnd_level: 1024,
                humidity: 49,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04d',
                },
            ],
            clouds: {
                all: 91,
            },
            wind: {
                speed: 3.13,
                deg: 151,
                gust: 4.2,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-04-17 06:00:00',
        },
        {
            dt: 1681722000,
            main: {
                temp: 12.89,
                feels_like: 11.44,
                temp_min: 12.89,
                temp_max: 12.89,
                pressure: 1026,
                sea_level: 1026,
                grnd_level: 1023,
                humidity: 46,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04d',
                },
            ],
            clouds: {
                all: 93,
            },
            wind: {
                speed: 5.04,
                deg: 149,
                gust: 5.78,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-04-17 09:00:00',
        },
        {
            dt: 1681732800,
            main: {
                temp: 13.45,
                feels_like: 12.16,
                temp_min: 13.45,
                temp_max: 13.45,
                pressure: 1025,
                sea_level: 1025,
                grnd_level: 1022,
                humidity: 50,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04d',
                },
            ],
            clouds: {
                all: 90,
            },
            wind: {
                speed: 6.09,
                deg: 151,
                gust: 6.86,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-04-17 12:00:00',
        },
        {
            dt: 1681743600,
            main: {
                temp: 12.32,
                feels_like: 11.15,
                temp_min: 12.32,
                temp_max: 12.32,
                pressure: 1025,
                sea_level: 1025,
                grnd_level: 1023,
                humidity: 59,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04d',
                },
            ],
            clouds: {
                all: 92,
            },
            wind: {
                speed: 5.39,
                deg: 154,
                gust: 6.67,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-04-17 15:00:00',
        },
        {
            dt: 1681754400,
            main: {
                temp: 11.94,
                feels_like: 10.86,
                temp_min: 11.94,
                temp_max: 11.94,
                pressure: 1025,
                sea_level: 1025,
                grnd_level: 1022,
                humidity: 64,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04n',
                },
            ],
            clouds: {
                all: 91,
            },
            wind: {
                speed: 4.32,
                deg: 172,
                gust: 5.88,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'n',
            },
            dt_txt: '2023-04-17 18:00:00',
        },
        {
            dt: 1681765200,
            main: {
                temp: 11.61,
                feels_like: 10.58,
                temp_min: 11.61,
                temp_max: 11.61,
                pressure: 1024,
                sea_level: 1024,
                grnd_level: 1021,
                humidity: 67,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04n',
                },
            ],
            clouds: {
                all: 96,
            },
            wind: {
                speed: 3.49,
                deg: 190,
                gust: 4.97,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'n',
            },
            dt_txt: '2023-04-17 21:00:00',
        },
        {
            dt: 1681776000,
            main: {
                temp: 11.18,
                feels_like: 10.05,
                temp_min: 11.18,
                temp_max: 11.18,
                pressure: 1024,
                sea_level: 1024,
                grnd_level: 1021,
                humidity: 65,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04n',
                },
            ],
            clouds: {
                all: 94,
            },
            wind: {
                speed: 3.86,
                deg: 174,
                gust: 5.7,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'n',
            },
            dt_txt: '2023-04-18 00:00:00',
        },
        {
            dt: 1681786800,
            main: {
                temp: 11.35,
                feels_like: 10.24,
                temp_min: 11.35,
                temp_max: 11.35,
                pressure: 1024,
                sea_level: 1024,
                grnd_level: 1021,
                humidity: 65,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 802,
                    main: 'Clouds',
                    description: 'scattered clouds',
                    icon: '03d',
                },
            ],
            clouds: {
                all: 50,
            },
            wind: {
                speed: 4.18,
                deg: 187,
                gust: 6.79,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-04-18 03:00:00',
        },
        {
            dt: 1681797600,
            main: {
                temp: 13.77,
                feels_like: 12.46,
                temp_min: 13.77,
                temp_max: 13.77,
                pressure: 1024,
                sea_level: 1024,
                grnd_level: 1021,
                humidity: 48,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 802,
                    main: 'Clouds',
                    description: 'scattered clouds',
                    icon: '03d',
                },
            ],
            clouds: {
                all: 26,
            },
            wind: {
                speed: 6.22,
                deg: 177,
                gust: 8.11,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-04-18 06:00:00',
        },
        {
            dt: 1681808400,
            main: {
                temp: 15.01,
                feels_like: 13.69,
                temp_min: 15.01,
                temp_max: 15.01,
                pressure: 1023,
                sea_level: 1023,
                grnd_level: 1020,
                humidity: 43,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 800,
                    main: 'Clear',
                    description: 'clear sky',
                    icon: '01d',
                },
            ],
            clouds: {
                all: 5,
            },
            wind: {
                speed: 6.89,
                deg: 166,
                gust: 8.72,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-04-18 09:00:00',
        },
        {
            dt: 1681819200,
            main: {
                temp: 14.82,
                feels_like: 13.45,
                temp_min: 14.82,
                temp_max: 14.82,
                pressure: 1022,
                sea_level: 1022,
                grnd_level: 1019,
                humidity: 42,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 800,
                    main: 'Clear',
                    description: 'clear sky',
                    icon: '01d',
                },
            ],
            clouds: {
                all: 5,
            },
            wind: {
                speed: 8.5,
                deg: 154,
                gust: 11.25,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-04-18 12:00:00',
        },
        {
            dt: 1681830000,
            main: {
                temp: 13.74,
                feels_like: 12.34,
                temp_min: 13.74,
                temp_max: 13.74,
                pressure: 1021,
                sea_level: 1021,
                grnd_level: 1019,
                humidity: 45,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 803,
                    main: 'Clouds',
                    description: 'broken clouds',
                    icon: '04d',
                },
            ],
            clouds: {
                all: 61,
            },
            wind: {
                speed: 5.2,
                deg: 157,
                gust: 8.35,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-04-18 15:00:00',
        },
    ],
    city: {
        id: 587081,
        name: 'Baku City',
        coord: {
            lat: 40.4093,
            lon: 49.8671,
        },
        country: 'AZ',
        population: 0,
        timezone: 14400,
        sunrise: 1681351555,
        sunset: 1681398961,
    },
};
